import type { Metadata } from "next";
import "./globals.css";
import { HeroProvider } from "@/providers/hero-ui";
import { Loader } from "@/shared/ui";
/* import { HeroProvider } from "@/providers/hero-ui"; */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-satoshi`}
      >
        <HeroProvider>
          <Loader
            theme="dark"
            classNames={{
              container: "-z-10"
            }}
          />
          {children}
        </HeroProvider>
      </body>
    </html>
  );
}
